// noinspection SpellCheckingInspection

import type { Song } from '../src/songs';

export const songList = [
    {"id": 1, "anime": "ADVANCED V.G 2 - OP", "name": "\"endless life\" by Masami Okui", "video": "https://files.catbox.moe/xms215.webm", "mp3": null},
    {"id": 2, "anime": "Akazukin Chacha - ED3", "name": "\"Youkoso Magical School e\" by Masami Suzuki & Magical Study", "video": "https://naedist.animemusicquiz.com/0pj16h.webm", "mp3": null},
    {"id": 3, "anime": "Akihabara Dennou-gumi - OP", "name": "\"Birth\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/kcxwhn.webm", "mp3": null},
    {"id": 4, "anime": "Akihabara Dennou-gumi - ED1", "name": "\"Taiyou no Hana\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/t9a61m.webm", "mp3": null},
    {"id": 5, "anime": "Akihabara Dennou-gumi - ED2", "name": "\"Taiyou no Hana ~Latin Jazz version~\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/77b8ke.webm", "mp3": null},
    {"id": 6, "anime": "Akihabara Dennou-gumi - ED3", "name": "\"Taiyou no Hana ~Classic version~\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/7dbuci.webm", "mp3": null},
    {"id": 7, "anime": "Akihabara Dennou-gumi - ED5", "name": "\"Birth-Epilogue.ver.-\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/j57iic.webm", "mp3": null},
    {"id": 8, "anime": "Akihabara Dennou-gumi - INS", "name": "\"AKA\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/dblswn.webm", "mp3": null},
    {"id": 9, "anime": "Akihabara Dennou-gumi: 2011-nen no Natsuyasumi - ED", "name": "\"HOT SPICE\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/q4lkcw.webm", "mp3": null},
    {"id": 10, "anime": "Akihabara Dennou-gumi: 2011-nen no Natsuyasumi - INS", "name": "\"Last Scene\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/xhrh7i.webm", "mp3": null},
    {"id": 11, "anime": "Ayakashi - ED", "name": "\"Kagaribi\" by Masami Okui", "video": "https://files.catbox.moe/nme14j.webm", "mp3": null},
    {"id": 12, "anime": "Bakuretsu Hunter - ED", "name": "\"MASK\" by Masami Okui & Kasumi Matsumura", "video": "https://naedist.animemusicquiz.com/h9m7ti.webm", "mp3": null},
    {"id": 13, "anime": "burst error: EVE The 1st - OP", "name": "\"TAKE MY BREATH AWAY\" by Masami Okui", "video": "https://files.catbox.moe/80rd2u.webm", "mp3": null},
    {"id": 14, "anime": "Compiler - OP", "name": "\"I WAS BORN TO FALL IN LOVE\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/2x23wl.webm", "mp3": null},
    {"id": 15, "anime": "Compiler - ED", "name": "\"FULL UP MIND\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/p76sxp.webm", "mp3": null},
    {"id": 16, "anime": "Cutey Honey - OP", "name": "\"Cutey Honey\" by Masami Okui", "video": "https://files.catbox.moe/00n5ls.webm", "mp3": null},
    {"id": 17, "anime": "Devilman - ED2", "name": "\"Kyou mo Dokoka de Devilman\" by Masami Okui", "video": "https://files.catbox.moe/kg36qp.webm", "mp3": null},
    {"id": 18, "anime": "Di Gi Charat - OP", "name": "\"only one, No.1\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/j6kwjt.webm", "mp3": null},
    {"id": 19, "anime": "Di Gi Charat Christmas Special - OP", "name": "\"Megami ni Naritai ~for a yours~\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/z0td1z.webm", "mp3": null},
    {"id": 20, "anime": "Di Gi Charat Summer Special - OP", "name": "\"CUTIE\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/345vb2.webm", "mp3": null},
    {"id": 21, "anime": "Fantasia - ED", "name": "\"Dare yori mo Zutto...\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/9q4gdn.webm", "mp3": null},
    {"id": 22, "anime": "Final Approach 2 ~1st priority~ Portable - OP", "name": "\"Starting Over\" by Masami Okui", "video": "https://files.catbox.moe/h6226t.webm", "mp3": null},
    {"id": 23, "anime": "Final Approach 2 ~1st Priority~ Portable - INS", "name": "\"GRADUATION\" by Masami Okui", "video": "https://files.catbox.moe/asscrn.webm", "mp3": null},
    {"id": 24, "anime": "Final Approach 2 ~1st Priority~ Portable - ED", "name": "\"Beloved\" by Masami Okui", "video": "https://files.catbox.moe/42go3y.webm", "mp3": null},
    {"id": 25, "anime": "Fuujin Ryouiki Eretzvaju - OP", "name": "\"Kiss in the dark\" by Masami Okui", "video": "https://files.catbox.moe/j56495.webm", "mp3": null},
    {"id": 26, "anime": "Fuyu no Rondo - OP", "name": "\"Melted Snow\" by Masami Okui", "video": "https://files.catbox.moe/1k0jat.webm", "mp3": null},
    {"id": 27, "anime": "Fuyu no Rondo - INS", "name": "\"Fuyu no Himawari\" by Masami Okui", "video": "https://files.catbox.moe/y3c9ic.webm", "mp3": null},
    {"id": 28, "anime": "Galaxy Angel A - ED3", "name": "\"In the Chaos\" by JAM Project featuring Masami Okui", "video": "https://naedist.animemusicquiz.com/zqpwam.webm", "mp3": null},
    {"id": 29, "anime": "Garo: Guren no Tsuki - OP3", "name": "\"Guren no Tsuki ~Kakusareshi Yami Monogatari~\" by Masami Okui (JAM Project)", "video": "https://naedist.animemusicquiz.com/eaor71.webm", "mp3": null},
    {"id": 30, "anime": "Garo: Vanishing Line - ED1", "name": "\"Sophia\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/b8le73.webm", "mp3": null},
    {"id": 31, "anime": "Ghost Sweeper Mikami - OP", "name": "\"GHOST SWEEPER\" by Masami Okui", "video": "https://files.catbox.moe/a9ne06.webm", "mp3": null},
    {"id": 32, "anime": "Grenadier: Hohoemi no Senshi - OP", "name": "\"KOHAKU\" by Masami Okui", "video": "https://files.catbox.moe/w7bnh5.webm", "mp3": null},
    {"id": 33, "anime": "Grisaia no Rakuen - OP", "name": "\"FISSION\" by Masami Okui", "video": "https://files.catbox.moe/wmglcy.webm", "mp3": null},
    {"id": 34, "anime": "GS Mikami: Gokuraku Daisakusen! - ED", "name": "\"My Jolly Days\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/otfyu7.webm", "mp3": null},
    {"id": 35, "anime": "GS Mikami: Gokuraku Daisakusen! - INS", "name": "\"BEATS the BAND\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/zh8weq.webm", "mp3": null},
    {"id": 36, "anime": "Haite Kudasai, Takamine-san - OP", "name": "\"Baby Baby Baby\" by Masami Okui with Bonjour Suzuki", "video": "https://naedist.animemusicquiz.com/x1bqcn.webm", "mp3": null},
    {"id": 37, "anime": "Hello, good-bye - OP", "name": "\"Good-bye Crisis\" by Masami Okui", "video": "https://files.catbox.moe/rqpof7.webm", "mp3": null},
    {"id": 38, "anime": "Hunter Hero - OP", "name": "\"Shizuka no Honoo\" by Masami Okui", "video": "https://files.catbox.moe/mscwvk.webm", "mp3": null},
    {"id": 39, "anime": "Jungle de Ikou! - OP", "name": "\"J\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/z0iwdy.webm", "mp3": null},
    {"id": 40, "anime": "Jungle de Ikou! - ED", "name": "\"spirit of the globe\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/ng635p.webm", "mp3": null},
    {"id": 41, "anime": "Junketsu no Mahou Shoujo -UNTITLED MAGICAL GIRL- - OP", "name": "\"Kibou no Tsubasa\" by Masami Okui", "video": "https://files.catbox.moe/0a05m2.webm", "mp3": null},
    {"id": 42, "anime": "Kaleido Star: Aratanaru Tsubasa - OP3", "name": "\"Tattoo Kiss\" by r.o.r/s", "video": "https://naedist.animemusicquiz.com/5c4gy1.webm", "mp3": null},
    {"id": 43, "anime": "Kaleido Star: Aratanaru Tsubasa - ED3", "name": "\"escape\" by r.o.r/s", "video": "https://naedist.animemusicquiz.com/87o1f8.webm", "mp3": null},
    {"id": 44, "anime": "Kanokon: Esuii - INS", "name": "\"Time Limit\" by Masami Okui", "video": "https://files.catbox.moe/i8xk92.webm", "mp3": null},
    {"id": 45, "anime": "Kidou Senkan Nadesico - OP", "name": "\"YOU GET TO BURNING\" by Masami Okui", "video": "https://files.catbox.moe/bgtdme.webm", "mp3": null},
    {"id": 46, "anime": "Kidou Shin Seiki Gundam X - OP1", "name": "\"DREAMS\" by Masami Okui", "video": "https://files.catbox.moe/xkswtl.webm", "mp3": null},
    {"id": 47, "anime": "Koisuru Otome to Shugo no Tate -The shield of AIGIS- - OP", "name": "\"LOVE SHIELD\" by Masami Okui", "video": "https://files.catbox.moe/4jivw8.webm", "mp3": null},
    {"id": 48, "anime": "Kore ga Watashi no Goshujin-sama - OP", "name": "\"TRUST\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/td3z25.webm", "mp3": null},
    {"id": 49, "anime": "Kyoukaisenjou no Horizon II - ED2", "name": "\"-Side SunRise- Sora no Uta\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/wpgbdb.webm", "mp3": null},
    {"id": 50, "anime": "Langrisser Re:Incarnation -Tensei- - OP", "name": "\"Blood Blade -Hikari to Yami no Kanata ni-\" by Masami Okui", "video": "https://files.catbox.moe/wx29qz.webm", "mp3": null},
    {"id": 51, "anime": "Last Order - OP", "name": "\"Abyss\" by Masami Okui", "video": "https://files.catbox.moe/qwxkab.webm", "mp3": null},
    {"id": 52, "anime": "Lost Universe - INS", "name": "\"spicy essence\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/7bpmc9.webm", "mp3": null},
    {"id": 53, "anime": "Lupin III - ED3", "name": "\"LOVE SQUALL\" by Masami Okui", "video": "https://files.catbox.moe/dftv56.webm", "mp3": null},
    {"id": 54, "anime": "Lupin III: Kiri no Elusive - ED", "name": "\"Lupin III Ai no Theme\" by Masami Okui", "video": "https://files.catbox.moe/06a49w.webm", "mp3": null},
    {"id": 55, "anime": "Mahoutsukai Tai! - ED", "name": "\"Mata Ashita\" by MASAMI", "video": "https://naedist.animemusicquiz.com/ruvnkn.webm", "mp3": null},
    {"id": 56, "anime": "Maitetsu - Last Run!! - ED1", "name": "\"Indivisible Love\" by Masami Okui", "video": "https://files.catbox.moe/c64eeh.webm", "mp3": null},
    {"id": 57, "anime": "Megami Tengoku - OP", "name": "\"GET MY WAY\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/6kqfah.webm", "mp3": null},
    {"id": 58, "anime": "Megami Tengoku - ED", "name": "\"DREAMING HEART\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/eh2g03.webm", "mp3": null},
    {"id": 59, "anime": "Muteki Kanban Musume - OP", "name": "\"WILD SPICE\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/vwylzt.webm", "mp3": null},
    {"id": 60, "anime": "Muv-Luv UNLIMITED - OP", "name": "\"sion\" by Masami Okui", "video": "https://files.catbox.moe/sa4z7s.webm", "mp3": null},
    {"id": 61, "anime": "Muv-Luv Alternative: photonmelodies♮ - OP", "name": "\"Hikari no Hana\" by Masami Okui", "video": "https://files.catbox.moe/3xdhro.webm", "mp3": null},
    {"id": 62, "anime": "Muv-Luv Alternative: Total Eclipse AVN - OP", "name": "\"INSANITY\" by Masami Okui", "video": "https://files.catbox.moe/x79eng.webm", "mp3": null},
    {"id": 63, "anime": "Muv-Luv Alternative: Total Eclipse AVN - ED1", "name": "\"TOTAL ECLIPSE\" by Masami Okui", "video": "https://files.catbox.moe/utxmex.webm", "mp3": null},
    {"id": 64, "anime": "Night Wizard The Animation - OP", "name": "\"KURENAI\" by Masami Okui", "video": "https://files.catbox.moe/nbtn0f.webm", "mp3": null},
    {"id": 65, "anime": "Night Wizard: The VIDEO GAME ~Denial of the World~ - ED", "name": "\"Fates\" by Masami Okui", "video": "https://files.catbox.moe/lunz6c.webm", "mp3": null},
    {"id": 66, "anime": "Ontama! - OP", "name": "\"Miracle Upper WL\" by Masami Okui feat. May'n", "video": "https://naedist.animemusicquiz.com/yfouy4.webm", "mp3": null},
    {"id": 67, "anime": "Princess Frontier Portable - OP", "name": "\"Dive to Future\" by Masami Okui", "video": "https://files.catbox.moe/o56a83.webm", "mp3": null},
    {"id": 68, "anime": "Puchi Pri*Yucie - ED", "name": "\"Ienai Kara -Piano quintetto-\" by Masami Okui", "video": "https://files.catbox.moe/o0eby9.webm", "mp3": null},
    {"id": 69, "anime": "Ray The Animation - OP", "name": "\"zero -G-\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/plb3tq.webm", "mp3": null},
    {"id": 70, "anime": "Ray The Animation - ED", "name": "\"Yuunagi\" by Masami Okui", "video": "https://files.catbox.moe/at5639.webm", "mp3": null},
    {"id": 71, "anime": "Reiwa no Di Gi Charat - OP", "name": "\"Aimaisa, Koufukuron\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/40eiih.webm", "mp3": null},
    {"id": 72, "anime": "Routes PE/PORTABLE - OP", "name": "\"Remote Viewing\" by Masami Okui", "video": "https://files.catbox.moe/eoisx2.webm", "mp3": null},
    {"id": 73, "anime": "Saber Marionette J - OP", "name": "\"Successful Mission\" by Masami Okui", "video": "https://files.catbox.moe/pp2m7k.webm", "mp3": null},
    {"id": 74, "anime": "Saber Marionette J to X - INS", "name": "\"Yakusoku no Chi\" by Masami Okui", "video": "https://files.catbox.moe/5xr52v.webm", "mp3": null},
    {"id": 75, "anime": "Saint Beast: Kouin Jojishi Tenshi Tan - OP", "name": "\"Divine love\" by Masami Okui", "video": "https://files.catbox.moe/a02mmn.webm", "mp3": null},
    {"id": 76, "anime": "Scrapped Princess - OP", "name": "\"Little Wing\" by JAM Project featuring Masami Okui", "video": "https://naedist.animemusicquiz.com/py5x7b.webm", "mp3": null},
    {"id": 77, "anime": "Shaman King - OP2", "name": "\"Northern Lights\" by Masami Okui", "video": "https://files.catbox.moe/v4g448.webm", "mp3": null},
    {"id": 78, "anime": "Shin Koihime†Musou: Otome Tairan - OP", "name": "\"Renka Tairan\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/6s62iv.webm", "mp3": null},
    {"id": 79, "anime": "Shinsetsu Ryouki no Ori - OP", "name": "\"Automation\" by Masami Okui", "video": "https://files.catbox.moe/e3hv7t.webm", "mp3": null},
    {"id": 80, "anime": "Shinseiki Evangelion - INS", "name": "\"Bay side love story -from Tokyo-\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/7idp95.webm", "mp3": null},
    {"id": 81, "anime": "Shinseiki Evangelion - INS", "name": "\"FACE\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/pcfmzk.webm", "mp3": null},
    {"id": 82, "anime": "Shinseiki Evangelion - INS", "name": "\"Ryoute Ippai no Yume\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/lt1xmu.webm", "mp3": null},
    {"id": 83, "anime": "Shinseiki Evangelion - INS", "name": "\"Fushigi na Yoru\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/nh6lbc.webm", "mp3": null},
    {"id": 84, "anime": "Shinseiki Evangelion - OP", "name": "\"Zankoku na Tenshi no Thesis\" by Masami Okui", "video": "https://files.catbox.moe/3cbq6i.webm", "mp3": null},
    {"id": 85, "anime": "Shinseiki Evangelion Gekijouban: Shi to Shinsei - ED", "name": "\"Tamashii no Refrain\" by Masami Okui", "video": "https://files.catbox.moe/pu4g8p.webm", "mp3": null},
    {"id": 86, "anime": "Shirobako - OP3", "name": "\"Takarabako -TREASURE BOX-\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/0kadnf.webm", "mp3": null},
    {"id": 87, "anime": "Shoujo Kakumei Utena - OP", "name": "\"Rondo-revolution\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/vxotr2.webm", "mp3": null},
    {"id": 88, "anime": "Shoujo Kakumei Utena - ED3", "name": "\"Rose & release\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/qgitqm.webm", "mp3": null},
    {"id": 89, "anime": "Shoujo Kakumei Utena - ED1", "name": "\"Truth\" by Masami Okui", "video": "https://files.catbox.moe/cyci22.webm", "mp3": null},
    {"id": 90, "anime": "Shoujo Kakumei Utena: Adolescence Mokushiroku - INS", "name": "\"Toki ni Ai wa\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/b93hme.webm", "mp3": null},
    {"id": 91, "anime": "Slayers - OP", "name": "\"Get along\" by Megumi Hayashibara & Masami Okui", "video": "https://naedist.animemusicquiz.com/a8zdlz.webm", "mp3": null},
    {"id": 92, "anime": "Slayers - ED", "name": "\"KUJIKENAIKARA!\" by Megumi Hayashibara & Masami Okui", "video": "https://naedist.animemusicquiz.com/jjyos7.webm", "mp3": null},
    {"id": 93, "anime": "Slayers Excellent - ED", "name": "\"Never die\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/u96vn9.webm", "mp3": null},
    {"id": 94, "anime": "Slayers Next - ED", "name": "\"Jama wa Sasenai\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/z3pi1k.webm", "mp3": null},
    {"id": 95, "anime": "Slayers Next - OP", "name": "\"Give a reason\" by Masami Okui", "video": "https://files.catbox.moe/vfzw1n.webm", "mp3": null},
    {"id": 96, "anime": "Solty Rei - ED1", "name": "\"Float ~Sora no Kanata de~\" by Masami Okui", "video": "https://files.catbox.moe/gavw5q.webm", "mp3": null},
    {"id": 97, "anime": "Sore wa Maichiru Sakura no You ni - OP", "name": "\"days\" by Masami Okui", "video": "https://files.catbox.moe/6yyc3b.webm", "mp3": null},
    {"id": 98, "anime": "Sore wa Maichiru Sakura no You ni - INS", "name": "\"beloved ~Sakura no Kanata e~\" by Masami Okui", "video": "https://files.catbox.moe/on604c.webm", "mp3": null},
    {"id": 99, "anime": "Soreyuke! Uchuu Senkan Yamamoto Yohko (1999) - OP", "name": "\"Tenshi no Kyuusoku\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/fil3iv.webm", "mp3": null},
    {"id": 100, "anime": "Soreyuke! Uchuu Senkan Yamamoto Yohko (1999) - ED", "name": "\"Lululu\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/fjfyx4.webm", "mp3": null},
    {"id": 101, "anime": "Soreyuke! Uchuu Senkan Yamamoto Yohko (1999) - INS", "name": "\"eternal promise\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/54k270.webm", "mp3": null},
    {"id": 102, "anime": "Soreyuke! Uchuu Senkan Yamamoto Yohko - ED", "name": "\"Shake it\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/qgopsn.webm", "mp3": null},
    {"id": 103, "anime": "Soreyuke! Uchuu Senkan Yamamoto Yohko II - OP", "name": "\"Souda, Zettai.\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/6z7hr7.webm", "mp3": null},
    {"id": 104, "anime": "Super Robot Taisen Original Generation: The Animation - ED1", "name": "\"Protect You\" by JAM Project feat. Masaaki Endoh/Masami Okui", "video": "https://naedist.animemusicquiz.com/64fk4d.webm", "mp3": null},
    {"id": 105, "anime": "Super Robot Wars Z - ED", "name": "\"Cosmic Dance\" by Masami Okui", "video": "https://files.catbox.moe/ek9lsk.webm", "mp3": null},
    {"id": 106, "anime": "Tales of Eternia - OP", "name": "\"Sora ni Kakeru Hashi\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/eu7s8g.webm", "mp3": null},
    {"id": 107, "anime": "Tales of Eternia - ED", "name": "\"I'd love you to touch me\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/sduavq.webm", "mp3": null},
    {"id": 108, "anime": "Tanoshii Willow Town - OP", "name": "\"Yume ni Konnichiwa Willow Town Monogatari\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/2jgjjh.webm", "mp3": null},
    {"id": 109, "anime": "Tanoshii Willow Town - ED", "name": "\"Liverpool e Oide\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/h3ak06.webm", "mp3": null},
    {"id": 110, "anime": "Uchuu no Kishi Tekkaman Blade 2 - OP", "name": "\"REINCARNATION\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/oo14vm.webm", "mp3": null},
    {"id": 111, "anime": "Uchuu no Kishi Tekkaman Blade 2 - ED1", "name": "\"It's DESTINY~Yatto Meguriaeta\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/kxov7r.webm", "mp3": null},
    {"id": 112, "anime": "Uchuu no Kishi Tekkaman Blade 2 - ED2", "name": "\"Live alone Sennen Tattemo\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/59335i.webm", "mp3": null},
    {"id": 113, "anime": "Yu-Gi-Oh! Duel Monsters - OP2", "name": "\"shuffle\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/1ytwdc.webm", "mp3": null},
    {"id": 114, "anime": "Yu-Gi-Oh! Duel Monsters - ED2", "name": "\"Ano Hi no Gogo\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/265e6p.webm", "mp3": null},
    {"id": 115, "anime": "Suzumiya Haruhi no Yuuutsu - INS", "name": "\"God knows...\" by Masami Okui", "video": "https://files.catbox.moe/g8n2a2.webm", "mp3": null},
    {"id": 116, "anime": "Natsu no Arashi! - INS", "name": "\"Shoujo A\" by Masami Okui", "video": "https://files.catbox.moe/cdjyqk.webm", "mp3": null},
    {"id": 117, "anime": "Ashita no Joe 2 - INS", "name": "\"Aoi Sangoshou\" by Masami Okui", "video": "https://files.catbox.moe/80tpjj.webm", "mp3": null},
    {"id": 118, "anime": "Salaryman ga Isekai ni Ittara Shitennou ni Natta Hanashi - INS", "name": "\"Mayonaka no Door ~ Stay With Me\" by Masami Okui", "video": "https://files.catbox.moe/uxemr8.webm", "mp3": null},
    {"id": 119, "anime": "City Hunter - OP1", "name": "\"CITY HUNTER ~Ai yo Kienaide~\" by Masami Okui", "video": "https://files.catbox.moe/h36sd7.webm", "mp3": null},
    {"id": 120, "anime": "Majo no Takkyuubin - ED", "name": "\"Yasashisa ni Tsutsumareta Nara\" by Masami Okui", "video": "https://files.catbox.moe/qxewnt.webm", "mp3": null},
    {"id": 121, "anime": "Snack Basue - ED1", "name": "\"Olivia wo Kikinagara\" by Masami Okui", "video": "https://files.catbox.moe/tt8kc7.webm", "mp3": null},
    {"id": 122, "anime": "Akihabara Dennou-gumi - INS", "name": "\"Koishimasho, Nebarimasho\" by Masami Okui", "video": "https://files.catbox.moe/srqajh.webm", "mp3": null},
    {"id": 123, "anime": "Shoujo Kakumei Utena: Adolescence Mokushiroku - INS", "name": "\"Rondo-revolution ~ Adolescence Rush\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/6w5gs4.webm", "mp3": null},
    {"id": 124, "anime": "Karaoke Senshi Mike Jirou - INS", "name": "\"Kawa no Nagare no You ni\" by Masami Okui", "video": "https://files.catbox.moe/wdxoat.webm", "mp3": null},
] satisfies Song[];
