// noinspection SpellCheckingInspection

import type { Song } from '../src/songs';

export const songList = [
             {"id": 1, "anime": "Boukyaku Battery - OP", "name": "\"Lilac\" by Mrs. GREEN APPLE", "video": "https://naedist.animemusicquiz.com/avs1ob.webm", "mp3": "https://www.youtube.com/watch?v=DO_aopUeFnw"},
    {"id": 2, "anime": "Enen no Shouboutai - OP1", "name": "\"Inferno\" by Mrs. GREEN APPLE", "video": "https://naedist.animemusicquiz.com/uazvg3.webm", "mp3": "https://www.youtube.com/watch?v=wNjvuRZtQeI"},
    {"id": 3, "anime": "Kusuriya no Hitorigoto 2nd Season - OP2", "name": "\"Kusushiki\" by Mrs. GREEN APPLE", "video": "https://naedist.animemusicquiz.com/070r4c.webm", "mp3": "https://www.youtube.com/watch?v=0Po9x1n0aQE"},
    {"id": 4, "anime": "Nana Maru San Batsu - OP", "name": "\"On My MiND\" by Mrs. GREEN APPLE", "video": "https://naedist.animemusicquiz.com/o37uye.webm", "mp3": "https://www.youtube.com/watch?v=jAD_y535Jog"},
    {"id": 5, "anime": "One Piece Film: Red - IN", "name": "\"Watashi wa Saikyou\" by Ado", "video": "https://nawdist.animemusicquiz.com/nq2ben.webm", "mp3": "https://www.youtube.com/watch?v=sk1Z-Hqwwog"},
    {"id": 6, "anime": "Puniru wa Kawaii Slime 2nd Season - ED", "name": "\"Ao to Natsu\" by Yu Sasahara", "video": "https://naedist.animemusicquiz.com/msclk0ux00ph2y55.webm", "mp3": "https://www.youtube.com/watch?v=OZOTSsmHEzQ"},
    {"id": 7, "anime": "Sousou no Frieren 2nd Season - OP", "name": "\"lulu.\" by Mrs. GREEN APPLE", "video": "https://naedist.animemusicquiz.com/sqy8ycjr34b4b8f4.webm", "mp3": "https://www.youtube.com/watch?v=4REuyY89tfw"},
    {"id": 8, "anime": "Tensei shitara Slime Datta Ken 3rd Season - OP2", "name": "\"Renacer Serenade\" by Momoiro Clover Z", "video": "https://naedist.animemusicquiz.com/iqoq8w.webm", "mp3": "https://www.youtube.com/watch?v=0d2rhw8kZso"},
    {"id": 9, "anime": "World Trigger 2nd Season - OP", "name": "\"Force\" by TOMORROW X TOGETHER", "video": "https://naedist.animemusicquiz.com/v0arh8.webm", "mp3": "https://www.youtube.com/watch?v=KCEohrmozm0"},
    {"id": 10, "anime": "Yu-Gi-Oh! Arc-V - ED4", "name": "\"Speaking\" by Mrs. GREEN APPLE", "video": "https://naedist.animemusicquiz.com/yu2ri1.webm", "mp3": "https://www.youtube.com/watch?v=ESgqymcTKzU"},
    {"id": 11, "anime": "Future Card Buddyfight - OP1", "name": "\"Card of the Future\" by Psychic Lover×Suara", "video": "https://naedist.animemusicquiz.com/qk68o6.webm", "mp3": "https://www.youtube.com/watch?v=LG8tg0hJNyY"},
    {"id": 12, "anime": "Future Card Buddyfight - OP2", "name": "\"Buddy Buddy BAAAAAN!!\" by Marie Mizuno & Shuuta Morishima", "video": "https://naedist.animemusicquiz.com/iisx95.webm", "mp3": "https://www.youtube.com/watch?v=Hg4FlpMKLrY"},
    {"id": 13, "anime": "Future Card Buddyfight - ED1", "name": "\"Buddy Buddy Fight!\" by Sora Tokui", "video": "https://naedist.animemusicquiz.com/jwu3ws.webm", "mp3": "https://www.youtube.com/watch?v=DPQtE37yBwM"},
    {"id": 14, "anime": "Future Card Buddyfight - ED2", "name": "\"Natsu-iro Fighting!!\" by Sora Tokui", "video": "https://naedist.animemusicquiz.com/4zydsl.webm", "mp3": "https://www.youtube.com/watch?v=W-CjmjZnvYo"},
    {"id": 15, "anime": "Future Card Buddyfight - ED3", "name": "\"Shiny Up!\" by Suzuko Mimori", "video": "https://naedist.animemusicquiz.com/g2zpzo.webm", "mp3": "https://www.youtube.com/watch?v=8uI2Tcgnm2Y"},
    {"id": 16, "anime": "Future Card Buddyfight 100 - OP1", "name": "\"Luminize\" by fripSide", "video": "https://naedist.animemusicquiz.com/sc7flb.webm", "mp3": "https://www.youtube.com/watch?v=KHnErFF8d2U"},
    {"id": 17, "anime": "Future Card Buddyfight 100 - OP2", "name": "\"Beyond the limits\" by Hideyuki Takahashi", "video": "https://naedist.animemusicquiz.com/dsdt96.webm", "mp3": "https://www.youtube.com/watch?v=EgCREU9-ZMg"},
    {"id": 18, "anime": "Future Card Buddyfight 100 - ED1", "name": "\"Buddy Lights\" by Soma Saito", "video": "https://naedist.animemusicquiz.com/xhjtm5.webm", "mp3": "https://www.youtube.com/watch?v=MYOMN7lHX6k"},
    {"id": 19, "anime": "Future Card Buddyfight 100 - ED2", "name": "\"Milky 100 World\" by Milky Holmes", "video": "https://naedist.animemusicquiz.com/pxr6ux.webm", "mp3": "https://www.youtube.com/watch?v=qOZM8T-sSIQ"},
    {"id": 20, "anime": "Future Card Buddyfight 100 - EP29 IN", "name": "\"GO GO BUDDY!!\" by Hideyuki Takahashi", "video": "https://naedist.animemusicquiz.com/jb2b01.webm", "mp3": "https://www.youtube.com/watch?v=YCnpd0fuPnM"},
    {"id": 21, "anime": "Future Card Buddyfight DDD - OP1", "name": "\"Chronograph\" by Takaaki Natsushiro", "video": "https://naedist.animemusicquiz.com/cwwckv.webm", "mp3": "https://www.youtube.com/watch?v=bsA7vPx4v4M"},
    {"id": 22, "anime": "Future Card Buddyfight DDD - OP2", "name": "\"DDD\" by Shouta Aoi", "video": "https://naedist.animemusicquiz.com/70tvd1.webm", "mp3": "https://www.youtube.com/watch?v=N47iEyJ4kwQ"},
    {"id": 23, "anime": "Future Card Buddyfight DDD - ED1", "name": "\"Waku☆Doki SHOOTER\" by Sora Tokui", "video": "https://naedist.animemusicquiz.com/hj51fh.webm", "mp3": "https://www.youtube.com/watch?v=kyvlL0BITVY"},
    {"id": 24, "anime": "Future Card Buddyfight DDD - ED2", "name": "\"Yume no Hikari, Kimi no Mirai\" by Aina Aiba", "video": "https://naedist.animemusicquiz.com/rlo52k.webm", "mp3": "https://www.youtube.com/watch?v=vEGXSfrYnv0"},
    {"id": 25, "anime": "Future Card Buddyfight DDD - ED3", "name": "\"Unite (Live Forever)\" by Bars & Melody", "video": "https://naedist.animemusicquiz.com/y4c4h2.webm", "mp3": "https://www.youtube.com/watch?v=EkYfnwnXDfs"},
    {"id": 26, "anime": "Future Card Buddyfight X - OP1", "name": "\"Brave Soul Fight!\" by Sora Tokui & Shuuta Morishima", "video": "https://naedist.animemusicquiz.com/3pwxpk.webm", "mp3": "https://www.youtube.com/watch?v=Qn-FYfL17O0"},
    {"id": 27, "anime": "Future Card Buddyfight X - OP2", "name": "\"Buddyfight×Buddyfighter\" by Jun Shirota", "video": "https://naedist.animemusicquiz.com/0e2ilx.webm", "mp3": "https://www.youtube.com/watch?v=skpynkvuw2s"},
    {"id": 28, "anime": "Future Card Buddyfight X - ED1", "name": "\"Mukaikaze ni Fight!\" by Ayana Kinoshita", "video": "https://naedist.animemusicquiz.com/8jr199.webm", "mp3": "https://www.youtube.com/watch?v=OfUmQnwpBrU"},
    {"id": 29, "anime": "Future Card Buddyfight X - ED2", "name": "\"B.O.F\" by Poppin'Party", "video": "https://naedist.animemusicquiz.com/m6phg6.webm", "mp3": "https://www.youtube.com/watch?v=dW25FkbQC58"},
    {"id": 30, "anime": "Future Card Buddyfight X - EP45 IN", "name": "\"Toshi Densetsu Robo Hanako WC no Uta\" by Yoshihisa Kawahara", "video": "https://files.catbox.moe/3ci10x.webm", "mp3": "https://files.catbox.moe/3ci10x.webm"},
    {"id": 31, "anime": "Future Card Shin Buddyfight - OP1", "name": "\"Saa Ikou!\" by Poppin'Party", "video": "https://naedist.animemusicquiz.com/m8f9rk.webm", "mp3": "https://www.youtube.com/watch?v=w5jX2B8W6l8"},
    {"id": 32, "anime": "Future Card Shin Buddyfight - ED1", "name": "\"Buddy☆Funny DAYS\" by Takumi Mano, Daiki Kobayashi, Shuuta Morishima", "video": "https://naedist.animemusicquiz.com/y23760.webm", "mp3": "https://www.youtube.com/watch?v=RrF5sdXn7jA"},
    {"id": 33, "anime": "Future Card Shin Buddyfight - ED2", "name": "\"Niji no Yakusoku\" by Shuuta Morishima", "video": "https://naedist.animemusicquiz.com/4jq2e5.webm", "mp3": "https://www.youtube.com/watch?v=wPZaP2I-yaY"},
] satisfies Song[];
