// noinspection SpellCheckingInspection

import type { Song } from '../src/songs';

export const songList = [
    {"id": 1, "anime": "A-Channel - OP", "name": "\"Morning Arch\" by Marina Kawano", "video": "https://naedist.animemusicquiz.com/q74oiv.webm", "mp3": null},
    {"id": 2, "anime": "Beelzebub - ED3", "name": "\"Nanairo☆Namida\" by Tomato n' Pine", "video": "https://naedist.animemusicquiz.com/pcj2k0.webm", "mp3": null},
    {"id": 3, "anime": "Bleach - OP5", "name": "\"Rolling star\" by YUI", "video": "https://naedist.animemusicquiz.com/zsclkk.webm", "mp3": null},
    {"id": 4, "anime": "Bleach - OP13", "name": "\"Ranbu no Melody\" by SID", "video": "https://naedist.animemusicquiz.com/mkl7ug.webm", "mp3": null},
    {"id": 5, "anime": "Boku dake ga Inai Machi - ED", "name": "\"Sore wa Chiisana Hikari no You na\" by Sayuri", "video": "https://naedist.animemusicquiz.com/8mw5en.webm", "mp3": null},
    {"id": 6, "anime": "Dragon Crisis! - OP", "name": "\"Immoralist\" by Yui Horie", "video": "https://naedist.animemusicquiz.com/sfc0xx.webm", "mp3": null},
    {"id": 7, "anime": "Eiken: Eiken-bu yori Ai o Komete - OP", "name": "\"Feel like our days\" by Tohko", "video": "https://naedist.animemusicquiz.com/wl4jqx.webm", "mp3": null},
    {"id": 8, "anime": "Ginga Ojou-sama Densetsu Yuna: Shinen no Fairy - OP", "name": "\"LIGHTNING HEART!\" by Chisa Yokoyama", "video": "https://naedist.animemusicquiz.com/zppstw.webm", "mp3": null},
    {"id": 9, "anime": "Granblue Fantasy the Animation - OP", "name": "\"GO\" by BUMP OF CHICKEN", "video": "https://naedist.animemusicquiz.com/6fbhxr.webm", "mp3": null},
    {"id": 10, "anime": "Horimiya - OP", "name": "\"Iro Kousui\" by Yoh Kamiyama", "video": "https://naedist.animemusicquiz.com/kt1nex.webm", "mp3": null},
    {"id": 11, "anime": "Horimiya: Piece - OP", "name": "\"Shiawase\" by Omoinotake", "video": "https://naedist.animemusicquiz.com/pl9aah.webm", "mp3": null},
    {"id": 12, "anime": "Horimiya: Piece - EP7 ED", "name": "\"Dokuro Ninja Konoha\" by Reina Kondo & Jun Fukuyama", "video": "https://naedist.animemusicquiz.com/or15bz.webm", "mp3": null},
    {"id": 13, "anime": "Kamichu! - OP", "name": "\"Hare Nochi Hare!\" by Maho Tomita", "video": "https://naedist.animemusicquiz.com/4agfjg.webm", "mp3": null},
    {"id": 14, "anime": "Kuroshitsuji: Kishuku Gakkou-hen - OP", "name": "\"Kyoushinsha no Parade - The Parade of Battlers\" by otoha", "video": "https://naedist.animemusicquiz.com/rgdrvs.webm", "mp3": null},
    {"id": 15, "anime": "Mahou Sensou - ED", "name": "\"Born to be\" by nano", "video": "https://naedist.animemusicquiz.com/oi3t2y.webm", "mp3": null},
    {"id": 16, "anime": "NHK ni Youkoso! - OP1", "name": "\"Puzzle\" by ROUND TABLE featuring Nino", "video": "https://naedist.animemusicquiz.com/erjzni.webm", "mp3": null},
    {"id": 17, "anime": "Occultic;Nine - OP", "name": "\"Seisuu 3 no Nijou\" by Kanako Itou", "video": "https://naedist.animemusicquiz.com/zqbedq.webm", "mp3": null},
    {"id": 18, "anime": "Persona 5 the Animation - OP1", "name": "\"BREAK IN TO BREAK OUT\" by Lyn", "video": "https://naedist.animemusicquiz.com/ac08r1.webm", "mp3": null},
    {"id": 19, "anime": "Persona 5 the Animation - OP2", "name": "\"Dark Sun...\" by Lyn", "video": "https://naedist.animemusicquiz.com/9x1xds.webm", "mp3": null},
    {"id": 20, "anime": "Psycho-Pass 2 - OP", "name": "\"Enigmatic Feeling\" by Ling tosite sigure", "video": "https://naedist.animemusicquiz.com/lwo7vy.webm", "mp3": null},
    {"id": 21, "anime": "R.O.D: The TV - OP", "name": "\"R.O.D\" by YKZ", "video": "https://naedist.animemusicquiz.com/y5ofbl.webm", "mp3": null},
    {"id": 22, "anime": "Saenai Heroine no Sodatekata ♭ - OP", "name": "\"Stella Breeze\" by Luna Haruna", "video": "https://naedist.animemusicquiz.com/n4wqlx.webm", "mp3": null},
    {"id": 23, "anime": "Sangenshoku - MV", "name": "\"Sangenshoku\" by YOASOBI", "video": "https://www.youtube.com/watch?v=nhOhFOoURnE", "mp3": null},
    {"id": 24, "anime": "Senkou no Night Raid - OP", "name": "\"Yakusoku\" by MUCC", "video": "https://naedist.animemusicquiz.com/hgi1lc.webm", "mp3": null},
    {"id": 25, "anime": "Shingeki no Kyojin - OP2", "name": "\"Jiyuu no Tsubasa\" by Linked Horizon", "video": "https://naedist.animemusicquiz.com/oaaxgi.webm", "mp3": null},
    {"id": 26, "anime": "Shinsekai yori - ED2", "name": "\"Yuki ni Saku Hana\" by Kana Hanazawa", "video": "https://naedist.animemusicquiz.com/4fsyac.webm", "mp3": null},
    {"id": 27, "anime": "Soreyuke! Uchuu Senkan Yamamoto Yohko II - OP", "name": "\"Souda, Zettai.\" by Masami Okui", "video": "https://naedist.animemusicquiz.com/6z7hr7.webm", "mp3": null},
    {"id": 28, "anime": "Speed Grapher - OP", "name": "\"Gravure no Bishoujo\" by Duran Duran", "video": "https://naedist.animemusicquiz.com/b4rfvd.webm", "mp3": null},
    {"id": 29, "anime": "Spy × Family - OP", "name": "\"Mixed Nuts\" by Official HIGE DANdism", "video": "https://naedist.animemusicquiz.com/pxds9u.webm", "mp3": null},
    {"id": 30, "anime": "Tenamonya Voyagers - OP", "name": "\"Geba Geba 90-pun! no Theme\" by Hiroshi Miyagawa", "video": "https://naedist.animemusicquiz.com/tw37j8.webm", "mp3": null},
    {"id": 31, "anime": "Tenamonya Voyagers - ED", "name": "\"Dare ka ga Kaze no Naka de\" by Ichiro Mizuki", "video": "https://naedist.animemusicquiz.com/ge271o.webm", "mp3": null},
    {"id": 32, "anime": "Tokyo 24-ku - OP", "name": "\"Papersky\" by Survive Said The Prophet", "video": "https://naedist.animemusicquiz.com/ddokb4.webm", "mp3": null},
    {"id": 33, "anime": "Tokyo Ravens - OP1", "name": "\"X-encounter\" by Maon Kurosaki", "video": "https://naedist.animemusicquiz.com/6xtjft.webm", "mp3": null},
    {"id": 34, "anime": "Uchuujin MuuMuu - ED2", "name": "\"Subarashii Hibi\" by Momo Harumi & Etsuko Kozakura", "video": "https://naedist.animemusicquiz.com/bguvjz7a2tfzbjad.webm", "mp3": null},
    {"id": 35, "anime": "Yama no Susume Second Season - OP1", "name": "\"Natsu-iro Present\" by Yuka Iguchi, Kana Asumi, Yoko Hikasa, Yui Ogura", "video": "https://naedist.animemusicquiz.com/f6nesz.webm", "mp3": null},
] satisfies Song[];
